### ISSUE TITLE
Sometimes Missing Icons

### ISSUE THREAD

**Issue by OMEGALULW** [TechHypno/ClassicFCT#1]
Idk what causes it but the spell icons are sometimes missing when attacking stuff.

**Comment by TechHypno** [comment]
Spell icons will be missing for stuff like auto attacks. From: ClownsterSent: niedziela, 29 listopada 2020 22:15To: TechHypno/ClassicFCTCc: SubscribedSubject: [TechHypno/ClassicFCT] Sometimes Missing Icons (#1) Idk what causes it but the spell icons are sometimes missing when attacking stuff.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by OMEGALULW** [comment]
When I tested it Mutilate was missing a few times, and Eviscerate was missing like once. It wasn't really happening often though.

**Comment by TechHypno** [comment]
Do you have merging enabled? If so then make sure you have either “Separate By Icon” or “Separate By Spell ID” checked. If that doesn’t help, please send me your configuraion file. Its located in “World of Warcraft\_retail_\WTF\Account\<Your Account ID>\SavedVariables\ClassicFCT.lua”. Best regards,TeHypno From: ClownsterSent: czwartek, 3 grudnia 2020 19:28To: TechHypno/ClassicFCTCc: TechHypno; CommentSubject: Re: [TechHypno/ClassicFCT] Sometimes Missing Icons (#1) When I tested it Mutilate was missing a few times, and Eviscerate was missing like once. It wasn't really happening often though.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
